@Restaurants.API_HostAddress = http://localhost:5090

@token=CfDJ8Cb8nu7S15JKoAbrplaT3KicI2klg-c863bGMReS1AaxZNjAZLuUdpqkzS57XzF8tZClC4RShlm8vcMbWaSU_oVkfM93_twJQznZ6sb6xSYkCadZU56B1tBxCdyXYbDjd6zwYf8PhPrITcyelZW_MxpvoP902pOmw9APSBaUKNDruuLkwRBdzOhOA5SC9GRuBlfdw0lIu-fECdtSGwYUSSr_5ezC211FbRR5og0x7WvUACC-pFgkS8YJUMRgPYgWKUaRWuwDqCHGEpKDWjbWYq8xOIrrLPAZLQbBIybnta0UPJ7FU3PVgSDNB8u4b0GKdCTsxL_sexPGxDDNB6NtpbkUB-vuoZUjj81YsGRj1fEUCNxQFGu2Iq7tHbyYemgZenSOrxWsLevPI95mrceMp-Ijer3TsgI1vAyhE9vT2yba8AmMvaeYBUs6mBNs5yj587DwDaz9qvJhkfReVsxLe_ujqBHQ_ODYe6TGXZfl55YlBjFjy7ZpQKYqTSguT5VA8L19mcTHjlHXSvW2kwoILtTvQXAULRVUk93HGyalJsAl3kVM1C_Xp19p1bgy7Z3oHsF8a8pXwTvn_N_1jjZWHaXXW2gq1RDu3oL7tmXtY5mSmbksYEDsYFQn8T3zZL5n_hkaNjzow9TjEzB3Hx8ouL084kNLgu-L5n_2cid8G6Axqb_1vWZ3aP70WKcY1m8sNQ

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

@id=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=2
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###
# CreateDishCommand
POST {{Restaurants.API_HostAddress}}/api/restaurants/11/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###
# GetAllDishesForRestaurant
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# GetDishByIdForRestaurant
@dishId=2
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
# DeleteDishes
@restaurantId=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# RegisterUser
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###
# LoginUser
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}