@Restaurants.API_HostAddress = http://localhost:5090

@token=CfDJ8Cb8nu7S15JKoAbrplaT3KgaPg6czKi1JM3tFUmw3wEnTUbA9W5PL46HmbFQWjrGeeYpUEnAgwp6wtLF0lr8S_6cLJRWxT8ZyuL70nQEaJluFKFf7S1CYj_Knv7q6DbxRLSQdrflhqy_SsXhZ-QTOYW5yV5VzcCbiU0QJYS-3tQ6tJKW6tFkbylTNcvF3nnQBXFbKGSTA9cfSA-Axpc4jiaGURp-qh7vV7gZgrowP2Xx1Q8Txff79A4eVsg1xsS-dAfSGcbDnKT6fsdH4MDnx_4ZOdqRjxLLht4BkkGOgvhcgvVmD577UnzinIHB9r5EV6Q75PvLAZ1rjlvOR-VPvbv9WUbw6_cnLCRlQlyupz_3i5ot2tuIUg0SA1dyb7OGTcFNABvYc109fDZjEAqUoAFqMTzbXLhRJjK439U6gjnDy9u8woJNn6_EBhj53ikYKp-dd4rs7VUB8CdzIEtEi2FlrvBuo-bVuFpnzmQrmdWn6An0I-4rEQJ_iVL1V6oOPeH4Up0rX5geQ4Od8KpMu50_U2l_IZ31fSYrTdqQ36mgaX92kw3nQoAeJokddDzNnVzppB-TbfkbUrUuNwM7zWQ-D_WwmcAv1R8fmX_vOqsfKaI-8ztOat7DfTGh_hsWojY1cAq3G3jhUx4KXNU3zSxZld-bFPgHnLF5QSGk0KvO1jkHul8TYYv0u6vgC-3HuOFK8EPc7CA6UJq689a5UMxbi4A7lbypo7D2k_TUa_HNuyeGGXx-3IgYF4Nsc4NjCsLxrBwgI-3izifkZjRs__c

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=kfc
Accept: application/json

###

@id=11
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
      "Name": "BLA restaurant",
      "Description": "A BLA restaurant serving a variety of delicious dishes.",
      "Category": "BLA",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

@id=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=11
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###
# CreateDishCommand
POST {{Restaurants.API_HostAddress}}/api/restaurants/11/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###
# GetAllDishesForRestaurant
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# GetDishByIdForRestaurant
@dishId=2
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
# DeleteDishes
@restaurantId=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# RegisterUser
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###
# LoginUser
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}

###
# UpdateEmailDoB
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "Polish",
  "DateOfBirth": "2010-01-01"
}