@Restaurants.API_HostAddress = http://localhost:5090

@token=CfDJ8Cb8nu7S15JKoAbrplaT3KiWXMZYuNha3063Z8mvYSMspLisT8POXwqijI_mAq9CLEbR-OtvbGIDTW9z-XXRDJe6yaSUuXLWcaaBVRGaGzmodJcwXk-u6ZCRXAeEcOLf86t_oVM0aABGJ36oJ_fc-CBRqj4q9Bxi6QSAVvLa50exxe_ACkJi5Vy-Eq6ICNLeSvSzlY_tAhPlbiHUHwR5_gr8bJbHMOMfxRjF95Xt3SxpgGi10_SH0ez-F4-IZxdKe5Gt9HCb9H58ihopRgfDclfoFT6uZu-mpK057nejUjef77rZbMiWCqPBJZNeqbbRDuzg1HmjskyMcNyUFNPGl6Lyot91iuS0RsqSJwW_2BIIfT8GaOdsx87UPn_baU1REmcJ9CVCAWHHZY4MUwoM88k-doQkI91bmrH6wi_DT7U5rUjn60MrdGOM86uMqNK7ffpMOfuCTPaGD-kUZTUNhCdyX2HnXin0EuZqwqF2phYyfdcK_Dp8cggo_p_MCwzkP8x913cuJHB2tWqfJqznrsMF_vRvunsbL3-_RhpMyUEidO0k2_70rFbvDp6aIvJlvWxk0PKkRzk6IiD9zK0Lne0e-IqAJfEkLhl7dOnvr-uO9365JKxb7fBT_pDsp_zgAXMmr-RQ5kfruMzrujZUdcwpBZMTRJVJkH4w_61MknXeZ1op4G0Yn7Ks5z7kFnvg2HAtpxbHYrhuBbT42XN9yYOHBL0hmt6oIopJfMF_ld8S-5bh7yJMMHbCECflrWrLNh5rBX4SW3joIpIXUn5-Ey4DGRWccVmRuIzx2cbWiSe-

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
      "Name": "BLA restaurant",
      "Description": "A BLA restaurant serving a variety of delicious dishes.",
      "Category": "BLA",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

@id=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

@id=2
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Content-Type: application/json
{
      "Name": "Owner2 restaurant2",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###
# CreateDishCommand
POST {{Restaurants.API_HostAddress}}/api/restaurants/11/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###
# GetAllDishesForRestaurant
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# GetDishByIdForRestaurant
@dishId=2
@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes/{{dishId}}

###
# DeleteDishes
@restaurantId=11
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###
# RegisterUser
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###
# LoginUser
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}